services:
  e-com-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  e-com-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      e-com-discovery-service:
        condition: service_healthy
  e-com-inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-com-config-service:
        condition: service_healthy
  e-com-order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-com-config-service:
        condition: service_healthy
  e-com-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-com-config-service:
        condition: service_healthy